update to v20230425

diff --git a/riscv-target/sail-riscv-c/device/rv64i_m/Zmmul/Makefile.include b/riscv-target/sail-riscv-c/device/rv64i_m/Zmmul/Makefile.include
--- a/riscv-target/sail-riscv-c/device/rv64i_m/Zmmul/Makefile.include
+++ b/riscv-target/sail-riscv-c/device/rv64i_m/Zmmul/Makefile.include
@@ -5,21 +5,37 @@ ifeq ($(shell command -v $(TARGET_SIM) 2> /dev/null),)
     $(error Target simulator executable '$(TARGET_SIM)` not found)
 endif
 
-RUN_TARGET=    $(TARGET_SIM) $(TARGET_FLAGS  \)
-        --test-signature=$(*).signature.output  \
-        $(<) 1>&2 2> $@
-
-RISCV_PREFIX   ?= riscv32-unknown-elf-
+RISCV_PREFIX   ?= riscv64-unknown-elf-
 RISCV_GCC      ?= $(RISCV_PREFIX)gcc
 RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
-RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles $(RVTEST_DEFINES)
+RISCV_GCC_OPTS ?= -g -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles $(RVTEST_DEFINES)
 
-COMPILE_TARGET=  \
-    $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS)  \
-        -I$(ROOTDIR)/riscv-test-env/  \
-        -I$(ROOTDIR)/riscv-test-env/p/  \
-        -I$(TARGETDIR)/$(RISCV_TARGET)/  \
-        -T$(ROOTDIR)/riscv-test-env/p/link.ld $$(<)  \
-        -o $$(@);  \
-    $$(RISCV_OBJDUMP) -D $$(@) > $$(@).objdump
+COMPILE_CMD = $$(RISCV_GCC) $(1) $$(RISCV_GCC_OPTS) \
+                    -I$(ROOTDIR)/riscv-test-suite/env/ \
+                    -I$(TARGETDIR)/$(RISCV_TARGET)/ \
+                    -T$(TARGETDIR)/$(RISCV_TARGET)/link.ld \
+                    $$(<) -o $$@
+
+OBJ_CMD = $$(RISCV_OBJDUMP) $$@ -D > $$@.objdump; \
+          $$(RISCV_OBJDUMP) $$@ --source > $$@.debug
+
+COMPILE_TARGET=        $(COMPILE_CMD); \
+        if [ $$$$? -ne 0 ] ; \
+                then \
+                echo "\e[31m$$(RISCV_GCC) failed for target $$(@) \e[39m" ; \
+                exit 1 ; \
+                fi ; \
+        $(OBJ_CMD); \
+        if [ $$$$? -ne 0 ] ; \
+                then \
+                echo "\e[31m $$(RISCV_OBJDUMP) failed for target $$(@) \e[39m" ; \
+                exit 1 ; \
+                fi ;
+
+RUN_CMD=    $(TARGET_SIM) $(TARGET_FLAGS)\
+        --test-signature=$(*).signature.output  \
+        $<   > $@
+
+RUN_TARGET=    $(RUN_CMD)
+
 
